### PR TITLE
Fixing test assertion

### PR DESCRIPTION
**Pull request by coheigea**
One of the unit tests is failing

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
i18n-apt is supposed to be compiled with jdk6. It seems you are compiling with latest version

see line 39 and 105 in [pom.xml](https://github.com/santhosh-tekuri/jlibs/blob/master/pom.xml)

you have to use toolchains.xml in .m2 directory. see build section [here](https://santhosh-tekuri.github.io/jlibs/)

**Comment by coheigea** [comment]
Does it matter? The fix should work for both...

**Comment by santhosh-tekuri** [comment]
I was wondering how I didn't get build error.

BTW, which jdk version you are using.
there is no guarantee that compiler error messages wont be changed from version to version

earlier in development, i noticed similar error messages when used jdk 1.7. so that time i enforced compiler version in pom.xml to avoid such build errors in future.

**Comment by coheigea** [comment]
I removed the toolchain config locally and used version JDK version 1.6.0-119

**Comment by santhosh-tekuri** [comment]
i am using 1.6.0_65. in java.util.MessageBundle.java I can see:

`throw new IllegalArgumentException("unknown format type at ");`

may be they changed in minor upgrade. will merge...

**Pull request merged**
